import test from 'node:test';import assert from 'node:assert/strict';
import {LEVELS} from '../src/content/levels.js';
import {ACTION,DELTA,at,bootAction,canDeploy,canTrain,checkObjective,configuration,createEpisode,encode,findEntity,launch,observeEcho,patchInteractionHint,step,walkable} from '../src/sim/core.js';
import {choose,rng,update,evaluate,trainBatch} from '../src/agents/q-learning.js';

function route(state,actor,target){
 const start=state[actor],queue=[{x:start.x,y:start.y}],seen=new Set([`${start.x},${start.y}`]),parent=new Map(),actionFor=new Map(),key=p=>`${p.x},${p.y}`;let found=null;
 while(queue.length){const cell=queue.shift();if(cell.x===target.x&&cell.y===target.y){found=cell;break;}for(const action of [1,2,3,4]){const d=DELTA[action],next={x:cell.x+d[0],y:cell.y+d[1]},k=key(next);if(seen.has(k)||!walkable(state,actor,next.x,next.y))continue;seen.add(k);parent.set(k,key(cell));actionFor.set(k,action);queue.push(next);}}
 assert.ok(found,`no ${actor} route to ${target.x},${target.y}`);const actions=[];for(let cursor=key(found);cursor!==key(start);cursor=parent.get(cursor))actions.push(actionFor.get(cursor));return actions.reverse();
}
function walkTo(state,actor,target){for(const action of route(state,actor,target))state=step(state,{[actor+'Action']:action}).state;return state;}
function runL01(){const level=LEVELS[0];let state=createEpisode(level),events=[];for(const id of ['patchRelayCell1','patchRelaySocket1']){const entity=findEntity(state,id);state=walkTo(state,'patch',entity);const out=step(state,{patchAction:ACTION.INTERACT});state=out.state;events.push(...out.events);}const config=configuration(level,{...level.learning.defaults,capabilities:state.capabilities}),trained=trainBatch(level,config,{episodes:level.learning.episodesPerBatch,seed:level.seeds.root});state={...state,config};state=launch(state);const random=rng(level.seeds.root+900000);for(let tick=0;tick<level.task.administrativeRolloutLimit&&state.echoActive;tick++){const out=step(state,{echoAction:choose(trained.q,encode(observeEcho(state)),random,0)});state=out.state;events.push(...out.events);}assert.equal(findEntity(state,'exitGate').open,true);state=walkTo(state,'patch',findEntity(state,'patchExit'));const out=step(state,{patchAction:ACTION.INTERACT});state=out.state;events.push(...out.events);return{state,events};}

test('L01 socket-installed action enables honest trained onboarding',()=>{const {state,events}=runL01();assert.equal(state.complete,true);assert.ok(at(state.patch,findEntity(state,'patchExit')));assert.ok(at(state.echo,findEntity(state,'echoExit')));assert.equal(events.filter(event=>event.type==='delivery').length,2);assert.equal(findEntity(state,'patchRelaySocket1').powered,true);assert.ok(state.capabilities.includes('act-east'));});
test('The opening learner cannot invent EAST before Patch installs it',()=>{for(const level of LEVELS.slice(0,2)){const config=configuration(level,{...level.learning.defaults,capabilities:[]}),trained=trainBatch(level,config,{episodes:level.learning.episodesPerBatch,seed:level.seeds.root}),result=evaluate(level,config,trained.q,{seed:level.seeds.root+900000});assert.equal(config.allowedActions.includes(ACTION.EAST),false,level.id);assert.notEqual(result.outcome,'delivered',level.id);}});
test('Terminal states absorb further commands',()=>{const {state}=runL01();assert.equal(step(state,{patchAction:2}).state,state);});
test('Transitions isolate mutable world state',()=>{const state=createEpisode(LEVELS[0]),before=JSON.stringify(state);step(state,{patchAction:2});assert.equal(JSON.stringify(state),before);});
test('Boundary collision changes facing but does not cross a wall',()=>{let state=createEpisode(LEVELS[0]),floor=state.level.playfields.patch[0].tiles,spot=null;for(let y=1;y<19&&!spot;y++)for(let x=1;x<19;x++)if(floor[y][x]==='.'&&floor[y-1][x]==='#'){spot={x,y};break;}state.patch={...state.patch,...spot};state=step(state,{patchAction:ACTION.NORTH}).state;assert.deepEqual([state.patch.x,state.patch.y],[spot.x,spot.y]);assert.equal(state.patch.facing,ACTION.NORTH);});
test('Patch and Echo occupy genuinely separate playfields',()=>{let state=createEpisode(LEVELS[1],{practice:true}),point={x:state.echo.x,y:state.echo.y,room:0};state.patch={...state.patch,...point};state.echo={...state.echo,...point};const out=step(state,{patchAction:ACTION.WAIT,echoAction:ACTION.WAIT}).state;assert.deepEqual([out.patch.x,out.patch.y],[point.x,point.y]);assert.deepEqual([out.echo.x,out.echo.y],[point.x,point.y]);});
test('Pickup requires INTERACT, not proximity',()=>{let state=createEpisode(LEVELS[0]),battery=findEntity(state,'patchRelayCell1');state=walkTo(state,'patch',battery);assert.equal(state.patch.cargo,null);state=step(state,{patchAction:ACTION.INTERACT}).state;assert.equal(state.patch.cargo,'patchRelayCell1');});
test('Repeated pickup cannot duplicate ownership',()=>{let state=createEpisode(LEVELS[0]),battery=findEntity(state,'patchRelayCell1');state.patch={...state.patch,x:battery.x,y:battery.y,room:battery.room};state=step(state,{patchAction:5}).state;state=step(state,{patchAction:5}).state;assert.equal(state.ledger.filter(key=>key==='pickup:patchRelayCell1').length,1);});
test('Default and repaired priority produce different genuine rewards',()=>{const level=LEVELS[1];for(const priority of ['scrap','delivery']){let state=createEpisode(level,{practice:true,config:configuration(level,{priority})}),scrap=state.entities.find(entity=>entity.kind==='scrap');state.echo={...state.echo,x:scrap.x,y:scrap.y,room:scrap.room};const out=step(state,{echoAction:5});assert.ok(Math.abs(out.reward-(state.config.reward.step+state.config.reward.scrap))<1e-10);}assert.notEqual(configuration(level,{priority:'scrap'}).reward.scrap,configuration(level,{priority:'delivery'}).reward.scrap);});
test('Scrap cannot satisfy a delivery objective',()=>{let state=createEpisode(LEVELS[1],{practice:true});for(const entity of state.entities)if(entity.kind==='scrap')entity.taken=true;state.patch={...state.patch,...findEntity(state,'patchExit')};assert.equal(checkObjective(state,state.level.task.objective),false);});
test('Patch cannot pick up Echo-only required cargo at the same coordinate',()=>{let state=createEpisode(LEVELS[1]),item=state.entities.find(entity=>entity.field==='echo'&&entity.required);state.patch={...state.patch,x:item.x,y:item.y,room:item.room};state=step(state,{patchAction:5}).state;assert.equal(state.patch.cargo,null);});
test('Laser phase is present in observation',()=>{const state=createEpisode(LEVELS[4],{practice:true});assert.notEqual(encode(observeEcho(state)),encode(observeEcho({...state,echoTick:1})));});
test('Caught takes precedence over otherwise successful state',()=>{let state=createEpisode(LEVELS[4],{practice:true}),laser=state.entities.find(entity=>entity.kind==='laser');state.echo={...state.echo,x:laser.x,y:laser.y,room:laser.room};state.echoTick=(laser.activePhases[0]-1+laser.period)%laser.period;state=step(state,{echoAction:0}).state;assert.equal(state.failed,true);assert.equal(state.complete,false);});
test('Simulation observation excludes model and RNG state',()=>{const observation=observeEcho(createEpisode(LEVELS[2],{practice:true}));assert.deepEqual(Object.keys(observation),['room','x','y','facing','cargo','scrapMask','phase']);});
test('Q-learning update equations retain exact contracts',()=>{const q={s:[2,0,0,0,0,0],next:[4,1,0,0,0,0]};assert.ok(Math.abs(update(q,'s',0,1,'next',false,.5,.9)-3.3)<1e-12);const terminal={s:[2,0,0,0,0,0],next:[4,1,0,0,0,0]};assert.equal(update(terminal,'s',0,1,'next',true,.5,.9),1.5);});
test('Discount setting reverses delayed reward ordering',()=>{assert.ok(10*.95**7>2);assert.ok(10*.5**7<2);assert.equal(configuration(LEVELS[2],{future:'near'}).gamma,.45);assert.equal(configuration(LEVELS[2],{future:'far'}).gamma,.96);});
test('Seeded PRNG produces reproducible samples',()=>{const a=rng(41001),b=rng(41001);assert.deepEqual(Array.from({length:100},a),Array.from({length:100},b));});
test('Evaluation does not mutate a frozen policy',()=>{const config=configuration(LEVELS[1],{priority:'delivery'}),q=trainBatch(LEVELS[1],config,{episodes:200,seed:1}).q,before=JSON.stringify(q);evaluate(LEVELS[1],config,q);assert.equal(JSON.stringify(q),before);});
test('Chapter 1 permits early deployment while L06 exposes a non-progressing rehearsal and later relays retain physical gates',()=>{const early=createEpisode(LEVELS[1]);assert.equal(canDeploy(early),true);assert.doesNotThrow(()=>launch(early));const l06=createEpisode(LEVELS[5]);assert.equal(canTrain(l06),true);assert.equal(canDeploy(l06),false);assert.throws(()=>launch(l06));const preview=launch(l06,{preview:true});assert.equal(preview.echoActive,true);assert.equal(preview.previewEcho,true);const later=createEpisode(LEVELS[7]);assert.equal(canDeploy(later),false);assert.throws(()=>launch(later));});
test('Echo delivery is terminal before Patch extraction',()=>{let state=createEpisode(LEVELS[1],{practice:true}),item=state.entities.find(entity=>entity.required),socket=state.entities.find(entity=>entity.kind==='socket'&&entity.accepts===item.id);state.echo={...state.echo,x:socket.x,y:socket.y,room:socket.room,cargo:item.id};item.taken=true;state=step(state,{echoAction:5}).state;assert.equal(state.courierDone,true);assert.equal(state.courierOutcome,'delivered');assert.equal(state.echoActive,false);});
test('Patch exit stays locked until Echo finishes and requires an explicit interaction',()=>{let state=createEpisode(LEVELS[1],{practice:true}),exit=findEntity(state,'patchExit'),gate=findEntity(state,'exitGate');state.patch={...state.patch,x:exit.x,y:exit.y,room:exit.room};state=step(state,{patchAction:ACTION.INTERACT}).state;assert.equal(!!findEntity(state,'patchExit').active,false);assert.equal(gate.open,false);const item=state.entities.find(entity=>entity.required),socket=state.entities.find(entity=>entity.kind==='socket'&&entity.accepts===item.id);state.echo={...state.echo,x:socket.x,y:socket.y,room:socket.room,cargo:item.id};item.taken=true;state=step(state,{echoAction:ACTION.INTERACT}).state;assert.equal(findEntity(state,'exitGate').open,true);assert.equal(state.complete,false);state=step(state,{patchAction:ACTION.INTERACT}).state;assert.equal(findEntity(state,'patchExit').active,true);});
test('Echo deployment budget pauses after delivery while Patch extracts',()=>{let state=createEpisode(LEVELS[9]),exit=findEntity(state,'echoExit');state={...state,echo:{...state.echo,x:exit.x,y:exit.y,room:exit.room},missionStarted:true,missionSteps:state.level.task.horizonSteps-1,echoActive:false,courierDone:true,courierOutcome:'delivered'};state=step(state,{patchAction:2}).state;assert.equal(state.missionSteps,state.level.task.horizonSteps-1);assert.equal(state.failed,false);});
test('Patch exploration never spends Echo energy before launch',()=>{const level=LEVELS[1];let state=createEpisode(level,{config:configuration(level)});for(let index=0;index<level.task.horizonSteps+8;index++)state=step(state,{patchAction:index%2?2:4}).state;assert.equal(state.echoSteps,0);assert.equal(state.failed,false);assert.equal(state.courierOutcome,null);});
test('A relay requires its physical capability before deployment',()=>{const state=createEpisode(LEVELS[7]),stage=state.level.task.echoStages[0];findEntity(state,'heavyGate').open=true;for(const id of stage.requirements){const entity=findEntity(state,id);if(entity.kind==='socket')entity.powered=true;else entity.active=true;}state.activeDock=stage.dockId;assert.equal(canDeploy(state),false);state.capabilities.push(stage.requiredCapability);assert.equal(canDeploy(state),true);});
test('A wrong cartridge locks its siblings and leaves the dock unavailable',()=>{let state=createEpisode(LEVELS[20]),puzzle=state.level.learning.capabilityPuzzle,wrong=state.entities.find(entity=>entity.kind==='cartridge'&&entity.capabilityId!==puzzle.required);state.patch={...state.patch,x:wrong.x,y:wrong.y,room:wrong.room};state=step(state,{patchAction:5}).state;assert.ok(state.capabilities.includes(wrong.capabilityId));assert.ok(state.entities.filter(entity=>entity.choiceGroup===wrong.choiceGroup&&entity.id!==wrong.id).every(entity=>entity.locked));assert.equal(state.capabilities.includes(puzzle.required),false);});
test('Patch portal preserves local coordinates and changes only Patch room',()=>{let state=createEpisode(LEVELS[7]),portal=state.entities.find(entity=>entity.kind==='portal'&&entity.field==='patch'&&entity.targetRoom===1);portal.open=true;state.patch={...state.patch,x:portal.x,y:portal.y,room:portal.room};const echoBefore={...state.echo};state=step(state,{patchAction:5}).state;assert.deepEqual([state.patch.x,state.patch.y,state.patch.room],[portal.x,portal.y,1]);assert.deepEqual(state.echo,echoBefore);});
test('Echo-powered portals cannot be bypassed after Patch turns their switch',()=>{let state=createEpisode(LEVELS[7]),stage=state.level.task.echoStages[0],portal=findEntity(state,stage.gateId),lever=findEntity(state,portal.requires);assert.equal(lever.opensAfterEcho,true);state.patch={...state.patch,x:lever.x,y:lever.y,room:lever.room};state=step(state,{patchAction:5}).state;assert.equal(findEntity(state,lever.id).active,true);assert.equal(findEntity(state,portal.id).open,false);state.patch={...state.patch,x:portal.x,y:portal.y,room:portal.room};assert.equal(patchInteractionHint(state).possible,false);state=step(state,{patchAction:5}).state;assert.equal(state.patch.room,portal.room);assert.equal(findEntity(state,portal.id).open,false);});
test('Echo training remains available before Patch completes a relay contract',()=>{for(const level of LEVELS.filter(level=>level.learning.mode!=='none')){const state=createEpisode(level);assert.equal(canTrain(state),true,level.id);}});
test('A relay probe can deliver without arming the final receiver',()=>{const level=LEVELS[7],stage=level.task.echoStages[0];let state=createEpisode(level,{config:configuration(level,{...level.learning.defaults,stageIndex:0,stageStart:stage.startId,stagePhase:stage.phase,capabilities:[stage.requiredCapability]})});findEntity(state,'heavyGate').open=true;for(const id of stage.requirements){const entity=findEntity(state,id);if(entity.kind==='socket')entity.powered=true;else entity.active=true;}state.activeDock=stage.dockId;state.capabilities=[stage.requiredCapability];state=launch(state);assert.equal(state.receiverReady,false);const item=state.entities.find(entity=>entity.required),socket=state.entities.find(entity=>entity.kind==='socket'&&entity.accepts===item.id);state.echo={...state.echo,x:socket.x,y:socket.y,room:socket.room,cargo:item.id};item.taken=true;state=step(state,{echoAction:5}).state;assert.equal(state.courierOutcome,'delivered');assert.equal(state.receiverReady,false);});
test('Patch patrol contact returns to the latest checkpoint without failing',()=>{let state=createEpisode(LEVELS[39]),sentry=state.entities.find(entity=>entity.kind==='sentry');assert.ok(sentry);state.patch={...state.patch,room:sentry.room,x:sentry.x,y:sentry.y};state.patchCheckpoint={room:sentry.room,x:Math.max(1,sentry.x-1),y:sentry.y,facing:2};const result=step(state,{patchAction:5});state=result.state;assert.ok(at(state.patch,state.patchCheckpoint));assert.equal(state.patchStrikes,1);assert.equal(state.failed,false);assert.ok(result.events.some(event=>event.type==='patch-hit'));});
test('Patch-only doors never leak into Echo observations',()=>{const state=createEpisode(LEVELS[7],{practice:true}),before=encode(observeEcho(state)),gate=state.entities.find(entity=>entity.kind==='gate'&&entity.patchOnly);gate.open=!gate.open;assert.equal(encode(observeEcho(state)),before);});
test('Relay power sockets require a physically carried Patch cell',()=>{let state=createEpisode(LEVELS[1]),cell=findEntity(state,'patchRelayCell1'),socket=findEntity(state,'patchRelaySocket1');state.patch={...state.patch,x:cell.x,y:cell.y,room:cell.room};state=step(state,{patchAction:5}).state;assert.equal(state.patch.cargo,cell.id);state.patch={...state.patch,x:socket.x,y:socket.y,room:socket.room};state=step(state,{patchAction:5}).state;assert.equal(findEntity(state,socket.id).powered,true);assert.equal(state.patch.cargo,null);});
test('Player sensor and reward choices change the real learner contract',()=>{const level=LEVELS[20],mission=createEpisode(level,{practice:true,config:configuration(level,{sensorSuite:'mission'})}),beacon=createEpisode(level,{practice:true,config:configuration(level,{sensorSuite:'beacon'})});assert.notEqual(encode(observeEcho(mission)),encode(observeEcho(beacon)));const balanced=configuration(level,{rewardProfile:'balanced'}),sparse=configuration(level,{rewardProfile:'sparse'});assert.notDeepEqual(balanced.reward,sparse.reward);assert.equal(sparse.reward.progress,0);});
test('Patch E affordance shares interaction rules and hides used levers',()=>{let state=createEpisode(LEVELS[2]),lever=findEntity(state,'securityLever1');state.patch={...state.patch,x:lever.x,y:lever.y,room:lever.room};assert.deepEqual({id:patchInteractionHint(state).entity.id,possible:patchInteractionHint(state).possible},{id:'securityLever1',possible:true});state=step(state,{patchAction:ACTION.INTERACT}).state;assert.equal(patchInteractionHint(state),null);assert.equal(findEntity(state,'securityLever1').active,true);});
test('Patch E affordance is red for an unpowered socket and locked exit',()=>{let state=createEpisode(LEVELS[1]),socket=findEntity(state,'patchRelaySocket1');state.patch={...state.patch,x:socket.x,y:socket.y,room:socket.room};assert.deepEqual({id:patchInteractionHint(state).entity.id,possible:patchInteractionHint(state).possible},{id:socket.id,possible:false});const exit=findEntity(state,'patchExit');state.patch={...state.patch,x:exit.x,y:exit.y,room:exit.room};assert.deepEqual({id:patchInteractionHint(state).entity.id,possible:patchInteractionHint(state).possible},{id:'patchExit',possible:false});findEntity(state,'exitGate').open=true;assert.equal(patchInteractionHint(state).possible,true);});
test('District 7 Echo patrol moves in the shared transition and is observable',()=>{let state=createEpisode(LEVELS[30],{practice:true}),hunter=state.entities.find(entity=>entity.kind==='echo-hunter'),before=observeEcho(state);assert.ok(hunter);assert.equal(typeof before.threatDistance,'number');const start={x:hunter.x,y:hunter.y};for(let tick=0;tick<3&&hunter.x===start.x&&hunter.y===start.y;tick++){state=step(state,{echoAction:ACTION.WAIT}).state;hunter=state.entities.find(entity=>entity.kind==='echo-hunter');}assert.notDeepEqual({x:hunter.x,y:hunter.y},start);assert.notEqual(encode(before),encode(observeEcho(state)));});
test('Mission learning focus remains explicit while the guided boot starts with an action repair',()=>{assert.deepEqual(new Set(LEVELS.map(level=>level.learning.puzzleFocus)),new Set(['state','actions','reward','practice','policy']));assert.deepEqual(LEVELS.slice(0,5).map(level=>level.learning.puzzleFocus),['actions','actions','reward','practice','policy']);for(let start=5;start<LEVELS.length;start+=5)assert.deepEqual(LEVELS.slice(start,start+5).map(level=>level.learning.puzzleFocus),['state','actions','reward','practice','policy']);});
