import test from 'node:test';import assert from 'node:assert/strict';
import {LEVELS} from '../src/content/levels.js';
import {createEpisode,configuration,step,walkable,checkObjective} from '../src/sim/core.js';
import {featureVector} from '../src/agents/feature-control.js';
import {trainDqnBatch,evaluateDqn} from '../src/agents/deep-control.js';
import {trainImitation,evaluateImitation} from '../src/agents/imitation.js';
import {parameterChecksum} from '../src/agents/neural.js';
import {freshSave,validateSave} from '../src/persistence/save.js';

const directions=[[0,0],[0,-1],[1,0],[0,1],[-1,0]];
function pathTo(state,target){const queue=[[state.echo.x,state.echo.y,[]]],seen=new Set([`${state.echo.x},${state.echo.y}`]);while(queue.length){const [x,y,path]=queue.shift();if(x===target.x&&y===target.y)return path;for(let action=1;action<=4;action++){const nx=x+directions[action][0],ny=y+directions[action][1],key=`${nx},${ny}`;if(!seen.has(key)&&walkable(state,'echo',nx,ny)){seen.add(key);queue.push([nx,ny,[...path,action]]);}}}throw new Error('No demonstration route.');}
function demonstration(level,config){let state=createEpisode(level,{practice:true,config}),examples=[],episodeId=`${level.id}-player-test`;while(!state.courierDone&&!state.failed){const target=state.echo.cargo?state.entities.find(entity=>entity.kind==='socket'&&entity.accepts===state.echo.cargo):state.entities.filter(entity=>entity.required&&!entity.taken&&!entity.delivered&&entity.kind!=='core').sort((a,b)=>(a.sequence??99)-(b.sequence??99))[0];for(const action of [...pathTo(state,target),5]){examples.push({input:featureVector(level,config,state),action,episodeId});state=step(state,{echoAction:action}).state;if(state.courierDone||state.failed)break;}}assert.equal(state.courierOutcome,'delivered');return examples;}

test('DQN uses only bounded real replay and a copied target network',()=>{const level=LEVELS[40],config=configuration(level,level.learning.defaults),trained=trainDqnBatch(level,config,{seed:level.seeds.root,episodes:level.learning.episodesPerBatch,scheduleEpisodes:level.learning.episodesPerBatch,maxTransitions:level.learning.transitionBudget});assert.ok(trained.snapshot.realTransitions<=level.learning.transitionBudget);assert.ok(trained.snapshot.replay.length<=level.learning.replayCap);assert.ok(trained.snapshot.optimizerUpdates>0);assert.ok(trained.snapshot.targetCopies>0);assert.notEqual(parameterChecksum(trained.snapshot.online),parameterChecksum(trained.snapshot.target));assert.equal(evaluateDqn(level,config,trained.snapshot,{seed:level.seeds.root+900000}).outcome,'delivered');const capped=trainDqnBatch(level,config,{snapshot:{...trained.snapshot,realTransitions:level.learning.transitionBudget},seed:2,episodes:10,maxTransitions:level.learning.transitionBudget});assert.equal(capped.episodes,0);assert.equal(capped.transitions,0);});

test('DQN checkpoint batches preserve the exact seeded random stream',()=>{const level=LEVELS[40],config=configuration(level,level.learning.defaults),options={seed:level.seeds.root,scheduleEpisodes:40,maxTransitions:1000},single=trainDqnBatch(level,config,{...options,episodes:40}).snapshot,first=trainDqnBatch(level,config,{...options,episodes:20}).snapshot,second=trainDqnBatch(level,config,{...options,snapshot:first,episodes:20,scheduleOffset:20}).snapshot;assert.equal(parameterChecksum(second.online),parameterChecksum(single.online));assert.equal(second.rngState,single.rngState);assert.equal(second.realTransitions,single.realTransitions);assert.equal(second.optimizerUpdates,single.optimizerUpdates);});

test('Behavioral cloning trains only from player-format pre-action labels',()=>{const level=LEVELS[50],config=configuration(level,level.learning.defaults),examples=demonstration(level,config),trained=trainImitation(level,config,{demonstrations:examples,seed:level.seeds.root});assert.equal(trained.snapshot.examples,examples.length);assert.equal(trained.snapshot.episodes,1);assert.ok(trained.snapshot.updates>0);assert.equal(evaluateImitation(level,config,trained.snapshot).outcome,'delivered');});

test('Neural snapshots, replay, and demonstrations survive bounded save validation',()=>{const dqnLevel=LEVELS[40],dqnConfig=configuration(dqnLevel,dqnLevel.learning.defaults),dqn=trainDqnBatch(dqnLevel,dqnConfig,{seed:1,episodes:8,scheduleEpisodes:8,maxTransitions:120}).snapshot,cloneLevel=LEVELS[50],cloneConfig=configuration(cloneLevel,cloneLevel.learning.defaults),examples=demonstration(cloneLevel,cloneConfig),cloned=trainImitation(cloneLevel,cloneConfig,{demonstrations:examples,seed:2}).snapshot,save=freshSave();save.completed=Array.from({length:50},(_,i)=>`L${String(i+1).padStart(2,'0')}`);save.currentLevel='L51';save.cartridges.L41={controls:{...dqnLevel.learning.defaults},snapshot:dqn,episodes:dqn.episodes,revision:1};save.cartridges.L51={controls:{...cloneLevel.learning.defaults},snapshot:cloned,demonstrations:examples,episodes:cloned.episodes,revision:1};const clean=validateSave(save);assert.equal(clean.cartridges.L41.snapshot.replay.length,dqn.replay.length);assert.equal(clean.cartridges.L51.demonstrations.length,examples.length);});

test('Final boss objective falls only after all declared shield deliveries',()=>{const level=LEVELS[59],state=createEpisode(level,{practice:true});const boss=state.entities.find(entity=>entity.kind==='boss');assert.equal(boss.stages,3);const objective=level.task.objective.children.find(child=>child.op==='bossDefeated');assert.equal(checkObjective(state,objective),false);for(const item of state.entities.filter(entity=>entity.required&&entity.kind!=='core').slice(0,3))item.delivered=true;assert.equal(checkObjective(state,objective),true);});
