import test from 'node:test';import assert from 'node:assert/strict';
import {freshSave,validateSave,parseSave,storeSave,loadSave,SAVE_KEY} from '../src/persistence/save.js';
import {LEVELS} from '../src/content/levels.js';
import {applyCapabilities} from '../src/content/capabilities.js';
import {effectiveEpisodes,effectiveSweeps,playerControlDefaults} from '../src/content/cartridge-controls.js';
import {createEpisode,step,configuration,launch,canDeploy,canTrain,findEntity,encode,observeEcho,at} from '../src/sim/core.js';
import {trainBatch,evaluate,choose,rng} from '../src/agents/q-learning.js';
test('Save round trip preserves settings and progress',()=>{const save=freshSave();save.completed=['L01'];save.currentLevel='L02';assert.deepEqual(parseSave(JSON.stringify(save)),save);});
test('Corrupt saves are not overwritten on load',()=>{let raw='{broken';const storage={getItem(){return raw;},setItem(k,v){raw=v;}};assert.ok(loadSave(storage).warning);assert.equal(raw,'{broken');});
test('Unknown save schema is rejected',()=>assert.throws(()=>validateSave({...freshSave(),schemaVersion:99})));
test('Oversized import is rejected before parsing',()=>assert.throws(()=>parseSave(' '.repeat(6000001))));
test('Nonfinite policy values are rejected',()=>{const s=freshSave();s.cartridges.L02={controls:{priority:'delivery',future:'far',curiosity:'curious'},q:{'8,5,2,-,000,0':[Infinity,0,0,0,0,0]}};assert.throws(()=>validateSave(s));});
test('Malicious policy object keys are rejected',()=>{const s=freshSave();s.cartridges.L02={controls:{priority:'delivery',future:'far',curiosity:'curious'},q:JSON.parse('{"__proto__":[0,0,0,0,0,0]}')};assert.throws(()=>validateSave(s));});
test('Cartridge compatibility contracts survive a save round trip',()=>{const s=freshSave();s.cartridges.L02={controls:{priority:'delivery',future:'far',curiosity:'curious'},q:{},episodes:1800,contract:'tabular-q-v1:L02'};assert.equal(parseSave(JSON.stringify(s)).cartridges.L02.contract,'tabular-q-v1:L02');});
test('Physical Echo capability choice survives a save round trip',()=>{const s=freshSave();s.cartridges.L02={controls:{priority:'delivery',future:'far',curiosity:'curious'},capabilities:['act-east'],q:{},episodes:1800};assert.deepEqual(parseSave(JSON.stringify(s)).cartridges.L02.capabilities,['act-east']);});
test('Retired practice-budget data migrates without affecting the mission contract',()=>{const level=LEVELS.find(level=>level.id==='L31'),s=freshSave();s.cartridges.L31={controls:{...playerControlDefaults(level),...level.learning.defaults,trainingBudget:'extended'},capabilities:['budget-brief'],snapshot:null};const restored=parseSave(JSON.stringify(s)).cartridges.L31;assert.equal('trainingBudget' in restored.controls,false);assert.equal(restored.capabilities,undefined);});
test('Practice batches are authored constants rather than selectable budgets',()=>{const episodeLevel=LEVELS.find(level=>level.id==='L02'),sweepLevel=LEVELS.find(level=>level.id==='L08');assert.equal(effectiveEpisodes(episodeLevel,{trainingBudget:'brief'}),effectiveEpisodes(episodeLevel,{trainingBudget:'exhaustive'}));assert.equal(effectiveSweeps(sweepLevel,{trainingBudget:'brief'}),effectiveSweeps(sweepLevel,{trainingBudget:'exhaustive'}));assert.equal('trainingBudget' in playerControlDefaults(episodeLevel),false);});
test('Every required physical capability produces a save-compatible real control contract',()=>{for(const level of LEVELS.filter(level=>level.learning.capabilityPuzzle)){const capabilityId=level.learning.capabilityPuzzle.required,controls=applyCapabilities({...playerControlDefaults(level),...level.learning.defaults},[capabilityId],level),common={controls,capabilities:[capabilityId]},mode=level.learning.mode,cartridge=['q-learning','sarsa'].includes(mode)?{...common,q:{},episodes:0}:['linear-sarsa','dyna-q','reinforce','reinforce-baseline','actor-critic','dqn','behavioral-cloning'].includes(mode)?{...common,snapshot:null,episodes:0,...(mode==='behavioral-cloning'?{demonstrations:[]}:{})}:mode==='prediction'?{...common,prediction:null,episodes:0}:{...common,evaluation:null};const save=freshSave();save.cartridges[level.id]=cartridge;assert.doesNotThrow(()=>validateSave(save),`${level.id} ${capabilityId}`);}});
test('A bounded prepared relay stage survives save validation',()=>{const s=freshSave();s.cartridges.L08={controls:{...LEVELS[7].learning.defaults},evaluation:null,preparedStage:1,contract:'known-policy-v1:L08'};assert.equal(parseSave(JSON.stringify(s)).cartridges.L08.preparedStage,1);s.cartridges.L08.preparedStage=99;assert.equal(parseSave(JSON.stringify(s)).cartridges.L08.preparedStage,undefined);});
test('Chapter 2 evaluation snapshots survive a save round trip',()=>{const s=freshSave();s.completed=['L01','L02','L03','L04','L05'];s.currentLevel='L06';s.cartridges.L06={controls:{representation:'cargo',policy:'depot-route',start:'junction-dock'},evaluation:{policyHash:'deadbeef',startValue:8.2,successProbability:1,stateCount:16,sweeps:17},contract:'known-policy-v1:L06'};assert.deepEqual(parseSave(JSON.stringify(s)).cartridges.L06.evaluation,s.cartridges.L06.evaluation);});
test('Oversized cartridge compatibility contracts are rejected',()=>{const s=freshSave();s.cartridges.L02={controls:{priority:'delivery',future:'far',curiosity:'curious'},q:{},episodes:0,contract:'x'.repeat(1001)};assert.throws(()=>validateSave(s));});
test('Training reward change does not change map or objective',()=>{const l=LEVELS[1],a=createEpisode(l,{config:configuration(l,{priority:'scrap'})}),b=createEpisode(l,{config:configuration(l,{priority:'delivery'})});assert.deepEqual(a.entities,b.entities);assert.deepEqual(a.level.task.objective,b.level.task.objective);});
test('Exactly sixty sequential twelve-district definitions are present',()=>{assert.deepEqual(LEVELS.map(l=>l.id),Array.from({length:60},(_,i)=>`L${String(i+1).padStart(2,'0')}`));for(let i=1;i<60;i++)assert.deepEqual(LEVELS[i].prerequisites,[LEVELS[i-1].id]);assert.equal(LEVELS.at(-1).alignment.status,'original-extension');});
test('Every mission provides independent complete 20x20 Patch and Echo maps',()=>{for(const level of LEVELS){assert.equal(level.playfields.size,20);for(const field of ['patch','echo']){assert.ok(level.playfields[field].length>0,`${level.id} ${field} rooms`);for(const room of level.playfields[field]){assert.equal(room.tiles.length,20);assert.ok(room.tiles.every(row=>row.length===20&&/^[#.]+$/.test(row)));}}const patchRoom=level.playfields.patch[level.actors.patchSpawn.room??0],echoRoom=level.playfields.echo[level.actors.echoSpawn.room??0];assert.equal(patchRoom.tiles[level.actors.patchSpawn.y][level.actors.patchSpawn.x],'.');assert.equal(echoRoom.tiles[level.actors.echoSpawn.y][level.actors.echoSpawn.x],'.');for(const entity of level.geometry.entities)assert.ok(['patch','echo'].includes(entity.field),`${level.id}:${entity.id} field`);}});
test('District borders shrink exactly and every floor tile is connected to its room entry',()=>{for(const level of LEVELS){const chapter=Number(level.chapterId.slice(1)),border=chapter===1?5:chapter===2?4:chapter===3?3:1;assert.equal(level.playfields.border,border,level.id);for(const field of ['patch','echo'])for(let roomIndex=0;roomIndex<level.playfields[field].length;roomIndex++){const tiles=level.playfields[field][roomIndex].tiles;for(let y=0;y<20;y++)for(let x=0;x<20;x++)if(x<border||y<border||x>=20-border||y>=20-border)assert.equal(tiles[y][x],'#',`${level.id} ${field} room ${roomIndex+1} border ${x},${y}`);const entry=roomIndex===0?level.actors[`${field}Spawn`]:level.geometry.entities.find(entity=>entity.kind==='portal'&&entity.field===field&&entity.targetRoom===roomIndex);assert.ok(entry,`${level.id} ${field} room ${roomIndex+1} entry`);const queue=[entry],seen=new Set([`${entry.x},${entry.y}`]);while(queue.length){const {x,y}=queue.shift();for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(tiles[ny]?.[nx]!=='.'||seen.has(key))continue;seen.add(key);queue.push({x:nx,y:ny});}}const floor=tiles.reduce((sum,row)=>sum+[...row].filter(tile=>tile==='.').length,0);assert.equal(seen.size,floor,`${level.id} ${field} room ${roomIndex+1} disconnected floor`);}}});
test('Chapter 1 can train and run anywhere while socket delivery changes the real contract',()=>{const level=LEVELS[1];let state=createEpisode(level);assert.equal(canTrain(state),true);assert.equal(canDeploy(state),true);const cell=findEntity(state,'patchRelayCell1'),socket=findEntity(state,'patchRelaySocket1');state.patch={...state.patch,x:cell.x,y:cell.y,room:cell.room};state=step(state,{patchAction:5}).state;state.patch={...state.patch,x:socket.x,y:socket.y,room:socket.room};state=step(state,{patchAction:5}).state;assert.ok(state.capabilities.includes(level.learning.capabilityPuzzle.required));assert.equal(applyCapabilities(level.learning.defaults,state.capabilities,level).allowedActions.includes(2),true);});
test('Pure kernel exactly repeats the same action trace',()=>{const l=LEVELS[1];const actions=Array.from({length:90},(_,i)=>({patchAction:i%6,echoAction:(i*3)%6}));function run(){let s=createEpisode(l,{practice:true});return actions.map(a=>{s=step(s,a).state;return JSON.stringify(s);});}assert.deepEqual(run(),run());});
test('L02-L05 prepared lanes can be solved by genuinely trained policies',()=>{
 for(const l of LEVELS.slice(1,5)){
  const c=configuration(l,{priority:'delivery',future:'far',curiosity:'curious',capabilities:[...new Set(l.geometry.entities.filter(entity=>entity.grantsCapability).map(entity=>entity.grantsCapability))]});const trained=trainBatch(l,c,{episodes:1800,seed:41005});const e=evaluate(l,c,trained.q);
  assert.equal(e.outcome,'delivered',l.id);
 }
});
test('Patch infiltration grows from two rooms to seven with milestone patrols',()=>{
 const samples=[8,11,21,31,41,51].map(number=>LEVELS[number-1]);
 assert.deepEqual(samples.map(level=>level.task.patchRoomCount),[2,3,4,5,6,7]);
 for(let index=1;index<samples.length;index++){
  assert.ok(samples[index].geometry.width>=samples[index-1].geometry.width);
  assert.ok(samples[index].geometry.height>samples[index-1].geometry.height);
 }
 for(const number of [10,15,20,30,40,50,55,60])assert.ok(LEVELS[number-1].task.patchSentryCount>0,`L${number} has no patrol escalation`);
});
test('Every Patch room keeps its authored objects and same-coordinate portals reachable',()=>{
 for(const level of LEVELS){for(let roomIndex=0;roomIndex<level.playfields.patch.length;roomIndex++){
  const tiles=level.playfields.patch[roomIndex].tiles,entry=roomIndex===0?level.actors.patchSpawn:level.geometry.entities.find(entity=>entity.kind==='portal'&&entity.field==='patch'&&entity.room===roomIndex&&entity.targetRoom===roomIndex-1);assert.ok(entry,`${level.id} room ${roomIndex+1} entry`);
  const queue=[entry],seen=new Set([`${entry.x},${entry.y}`]);while(queue.length){const current=queue.shift();for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]]){const x=current.x+dx,y=current.y+dy,key=`${x},${y}`;if(seen.has(key)||tiles[y]?.[x]!=='.')continue;seen.add(key);queue.push({x,y});}}
  for(const entity of level.geometry.entities.filter(entity=>entity.field==='patch'&&(entity.room??0)===roomIndex))assert.ok(seen.has(`${entity.x},${entity.y}`),`${level.id} room ${roomIndex+1} cannot reach ${entity.id}`);
 }}
});
test('Progressive missions require multiple staged Echo activations with an honest final delivery',()=>{
 for(const level of LEVELS.slice(7)){
  const number=Number(level.id.slice(1)),expected=number>=51?5:number>=40?4:number>=31?3:2,stages=level.task.echoStages;assert.equal(stages.length,expected,level.id);
  assert.equal(stages.at(-1).final,true,level.id);assert.equal(stages.at(-1).dockId,'practiceDock',level.id);
  for(const stage of stages.slice(0,-1)){assert.ok(stage.gateId,`${level.id} ${stage.id} has no portal`);assert.equal(findEntity(createEpisode(level),stage.gateId).kind,'portal');}
 }
});
test('Physical capability sources match the early socket flow and later choice forks',()=>{for(const level of LEVELS.filter(level=>level.id!=='L60')){const chapter=Number(level.chapterId.slice(1)),count=level.learning.capabilityPuzzle.options.length;if(chapter===1){assert.ok(level.geometry.entities.some(entity=>entity.kind==='socket'&&entity.grantsCapability===level.learning.capabilityPuzzle.required),level.id);continue;}assert.ok(count>=2,level.id);if(chapter>=9)assert.ok(count>=3,level.id);assert.ok(level.geometry.entities.some(entity=>entity.kind==='cartridge'&&entity.capabilityId===level.learning.capabilityPuzzle.required),level.id);assert.ok(level.learning.capabilityPuzzle.options.every(id=>!['budget-brief','budget-deep'].includes(id)),level.id);}});
