export const AUDIO = {
  "screen_landing": {
    "id": "screen_landing",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 42.666666666666664,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Warm cinematic invitation; celeste, soft electric keys and a small mechanical pulse. Role: screen",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/screen_landing.mp3"
  },
  "screen_menu": {
    "id": "screen_menu",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 38.4,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Playful maintenance-elevator groove; rounded bass, brushed clicks and electric piano. Role: screen",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/screen_menu.mp3"
  },
  "screen_settings": {
    "id": "screen_settings",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 53.333333333333336,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Unhurried glass notes and soft suspended pads; leaves room for interface sounds. Role: screen",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/screen_settings.mp3"
  },
  "screen_map": {
    "id": "screen_map",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 40.0,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Curious mallets, a gentle pulse and lights appearing across the city. Role: screen",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/screen_map.mp3"
  },
  "ch01_scrapyard_base": {
    "id": "ch01_scrapyard_base",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 62.60868480725624,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rusty tuned percussion, soft plucks and an optimistic mechanical shuffle. Role: base",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch01_scrapyard_base.mp3"
  },
  "ch01_scrapyard_alert": {
    "id": "ch01_scrapyard_alert",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 62.60868480725624,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rusty tuned percussion, soft plucks and an optimistic mechanical shuffle. Role: alert",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch01_scrapyard_alert.mp3"
  },
  "ch01_scrapyard_extraction": {
    "id": "ch01_scrapyard_extraction",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 62.60868480725624,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rusty tuned percussion, soft plucks and an optimistic mechanical shuffle. Role: extraction",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch01_scrapyard_extraction.mp3"
  },
  "ch02_transit_depot_base": {
    "id": "ch02_transit_depot_base",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 53.333333333333336,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rail-like ticks, moving bass and clean repeating synth patterns. Role: base",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch02_transit_depot_base.mp3"
  },
  "ch02_transit_depot_alert": {
    "id": "ch02_transit_depot_alert",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 53.333333333333336,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rail-like ticks, moving bass and clean repeating synth patterns. Role: alert",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch02_transit_depot_alert.mp3"
  },
  "ch02_transit_depot_extraction": {
    "id": "ch02_transit_depot_extraction",
    "category": "music",
    "gain": 1,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 53.333333333333336,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Rail-like ticks, moving bass and clean repeating synth patterns. Role: extraction",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch02_transit_depot_extraction.mp3"
  },
  "ch03_switchworks_base": {"id":"ch03_switchworks_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":49.65517006802721,"cooldownMs":0,"maxVoices":1,"description":"Clockwork counter-rhythms, tuned metal and precise interlocking arpeggios. Role: base","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch03_switchworks_base.mp3"},
  "ch03_switchworks_alert": {"id":"ch03_switchworks_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":49.65517006802721,"cooldownMs":0,"maxVoices":1,"description":"Clockwork counter-rhythms, tuned metal and precise interlocking arpeggios. Role: alert","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch03_switchworks_alert.mp3"},
  "ch03_switchworks_extraction": {"id":"ch03_switchworks_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":49.65517006802721,"cooldownMs":0,"maxVoices":1,"description":"Clockwork counter-rhythms, tuned metal and precise interlocking arpeggios. Role: extraction","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch03_switchworks_extraction.mp3"},
  "ch04_courier_quarter_base": {"id":"ch04_courier_quarter_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":56.470589569161,"cooldownMs":0,"maxVoices":1,"description":"Bouncy parcel-delivery rhythm, pizzicato-like plucks and relaxed electric keys. Role: base","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch04_courier_quarter_base.mp3"},
  "ch04_courier_quarter_alert": {"id":"ch04_courier_quarter_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":56.470589569161,"cooldownMs":0,"maxVoices":1,"description":"Bouncy parcel-delivery rhythm, pizzicato-like plucks and relaxed electric keys. Role: alert","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch04_courier_quarter_alert.mp3"},
  "ch04_courier_quarter_extraction": {"id":"ch04_courier_quarter_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":56.470589569161,"cooldownMs":0,"maxVoices":1,"description":"Bouncy parcel-delivery rhythm, pizzicato-like plucks and relaxed electric keys. Role: extraction","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch04_courier_quarter_extraction.mp3"},
  "ch05_neon_market_base": {"id":"ch05_neon_market_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":51.42857142857143,"cooldownMs":0,"maxVoices":1,"description":"Rounded neon synth bass, offbeat chords and a restrained night-market melody. Role: base","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch05_neon_market_base.mp3"},
  "ch05_neon_market_alert": {"id":"ch05_neon_market_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":51.42857142857143,"cooldownMs":0,"maxVoices":1,"description":"Rounded neon synth bass, offbeat chords and a restrained night-market melody. Role: alert","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch05_neon_market_alert.mp3"},
  "ch05_neon_market_extraction": {"id":"ch05_neon_market_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":51.42857142857143,"cooldownMs":0,"maxVoices":1,"description":"Rounded neon synth bass, offbeat chords and a restrained night-market melody. Role: extraction","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch05_neon_market_extraction.mp3"},
  "ui_hover_01": {
    "id": "ui_hover_01",
    "category": "sfx",
    "gain": 0.45,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Quiet tactile hover tick.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_hover_01.wav"
  },
  "ui_press": {
    "id": "ui_press",
    "category": "sfx",
    "gain": 0.6,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 50,
    "maxVoices": 3,
    "description": "Button depressed.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_press.wav"
  },
  "ui_confirm": {
    "id": "ui_confirm",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Confirm selection.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_confirm.wav"
  },
  "ui_back": {
    "id": "ui_back",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Back or cancel.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_back.wav"
  },
  "ui_denied": {
    "id": "ui_denied",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Unavailable action; gentle descending indication.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_denied.wav"
  },
  "ui_save": {
    "id": "ui_save",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 1500,
    "maxVoices": 3,
    "description": "Local save confirmed; do not play every autosave.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ui_save.wav"
  },
  "patch_step_metal_01": {
    "id": "patch_step_metal_01",
    "category": "sfx",
    "gain": 0.5,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 4,
    "description": "Patch metal footstep variant.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_step_metal_01.wav"
  },
  "patch_step_metal_02": {
    "id": "patch_step_metal_02",
    "category": "sfx",
    "gain": 0.5,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 4,
    "description": "Patch metal footstep variant.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_step_metal_02.wav"
  },
  "patch_interact": {
    "id": "patch_interact",
    "category": "sfx",
    "gain": 0.75,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Tool arm engages a fixture.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_interact.wav"
  },
  "patch_push_start": {
    "id": "patch_push_start",
    "category": "sfx",
    "gain": 0.75,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Begin pushing a crate.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_push_start.wav"
  },
  "patch_carry_pickup": {
    "id": "patch_carry_pickup",
    "category": "sfx",
    "gain": 0.75,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Pick up a heavy object.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_carry_pickup.wav"
  },
  "patch_bump": {
    "id": "patch_bump",
    "category": "sfx",
    "gain": 0.38,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 250,
    "maxVoices": 3,
    "description": "Soft collision feedback.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/patch_bump.wav"
  },
  "echo_boot": {
    "id": "echo_boot",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Echo powers up.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_boot.wav"
  },
  "echo_ack_01": {
    "id": "echo_ack_01",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Friendly affirmative robot phrase.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_ack_01.wav"
  },
  "echo_confused": {
    "id": "echo_confused",
    "category": "sfx",
    "gain": 0.6,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 2000,
    "maxVoices": 3,
    "description": "Questioning robot phrase.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_confused.wav"
  },
  "echo_happy_01": {
    "id": "echo_happy_01",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Happy little response.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_happy_01.wav"
  },
  "echo_scan": {
    "id": "echo_scan",
    "category": "sfx",
    "gain": 0.48,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 900,
    "maxVoices": 3,
    "description": "Brief state-scanner sweep.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_scan.wav"
  },
  "echo_delivery": {
    "id": "echo_delivery",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 600,
    "maxVoices": 3,
    "description": "Successful autonomous handoff.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/echo_delivery.wav"
  },
  "item_scrap_01": {
    "id": "item_scrap_01",
    "category": "sfx",
    "gain": 0.55,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Scrap pickup variant.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/item_scrap_01.wav"
  },
  "item_fuse": {
    "id": "item_fuse",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Fuse collected.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/item_fuse.wav"
  },
  "item_core": {
    "id": "item_core",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 1000,
    "maxVoices": 3,
    "description": "Relay core acquired.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/item_core.wav"
  },
  "door_open": {
    "id": "door_open",
    "category": "sfx",
    "gain": 0.75,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Powered shutter opens.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/door_open.wav"
  },
  "lever_pull": {
    "id": "lever_pull",
    "category": "sfx",
    "gain": 0.75,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 100,
    "maxVoices": 3,
    "description": "Mechanical lever reaches detent.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/lever_pull.wav"
  },
  "terminal_accept": {
    "id": "terminal_accept",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Terminal accepts the interaction.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/terminal_accept.wav"
  },
  "laser_caught": {
    "id": "laser_caught",
    "category": "sfx",
    "gain": 0.66,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 600,
    "maxVoices": 3,
    "description": "Nonviolent caught or stunned cue.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/laser_caught.wav"
  },
  "learning_launch": {
    "id": "learning_launch",
    "category": "sfx",
    "gain": 0.7,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 90,
    "maxVoices": 3,
    "description": "Begin a bounded practice session.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/learning_launch.wav"
  },
  "learning_session_complete": {
    "id": "learning_session_complete",
    "category": "sfx",
    "gain": 0.48,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 3000,
    "maxVoices": 3,
    "description": "One practice session completes, never each gradient update.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/learning_session_complete.wav"
  },
  "attempt_reset": {
    "id": "attempt_reset",
    "category": "sfx",
    "gain": 0.6,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 500,
    "maxVoices": 3,
    "description": "Restart an attempt without implying memory was erased.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/attempt_reset.wav"
  },
  "ch01_scrapyard_ambience": {
    "id": "ch01_scrapyard_ambience",
    "category": "ambience",
    "gain": 0.5,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 16.0,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Low environmental bed for Small Sparks.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch01_scrapyard_ambience.mp3"
  },
  "ch02_transit_depot_ambience": {
    "id": "ch02_transit_depot_ambience",
    "category": "ambience",
    "gain": 0.5,
    "loop": true,
    "loopStart": 0,
    "loopEnd": 16,
    "cooldownMs": 0,
    "maxVoices": 1,
    "description": "Low environmental bed for Last Service.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/ch02_transit_depot_ambience.mp3"
  },
  "stinger_heist_clear": {
    "id": "stinger_heist_clear",
    "category": "stinger",
    "gain": 0.9,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 1200,
    "maxVoices": 1,
    "description": "Successful extraction; quick warm resolution.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/stinger_heist_clear.mp3"
  },
  "stinger_retry": {
    "id": "stinger_retry",
    "category": "stinger",
    "gain": 0.9,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 1200,
    "maxVoices": 1,
    "description": "Gentle failure; invites another attempt.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/stinger_retry.mp3"
  },
  "stinger_district_restored": {
    "id": "stinger_district_restored",
    "category": "stinger",
    "gain": 0.9,
    "loop": false,
    "loopStart": null,
    "loopEnd": null,
    "cooldownMs": 1200,
    "maxVoices": 1,
    "description": "Relay core restores the district.",
    "provenance": "Original procedural composition and synthesis; no external samples.",
    "path": "public/assets/audio/stinger_district_restored.mp3"
  },
  "ch06_modular_foundry_base": {"id":"ch06_modular_foundry_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":48,"cooldownMs":0,"maxVoices":1,"description":"Assembly in Motion base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch06_modular_foundry_base.mp3"},
  "ch06_modular_foundry_alert": {"id":"ch06_modular_foundry_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":48,"cooldownMs":0,"maxVoices":1,"description":"Assembly in Motion alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch06_modular_foundry_alert.mp3"},
  "ch06_modular_foundry_extraction": {"id":"ch06_modular_foundry_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":48,"cooldownMs":0,"maxVoices":1,"description":"Assembly in Motion extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch06_modular_foundry_extraction.mp3"},
  "ch07_clockwork_docks_base": {"id":"ch07_clockwork_docks_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":60,"cooldownMs":0,"maxVoices":1,"description":"Tides and Gears base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch07_clockwork_docks_base.mp3"},
  "ch07_clockwork_docks_alert": {"id":"ch07_clockwork_docks_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":60,"cooldownMs":0,"maxVoices":1,"description":"Tides and Gears alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch07_clockwork_docks_alert.mp3"},
  "ch07_clockwork_docks_extraction": {"id":"ch07_clockwork_docks_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":60,"cooldownMs":0,"maxVoices":1,"description":"Tides and Gears extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch07_clockwork_docks_extraction.mp3"},
  "ch08_skybridge_base": {"id":"ch08_skybridge_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":64,"cooldownMs":0,"maxVoices":1,"description":"Above the Quiet City base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch08_skybridge_base.mp3"},
  "ch08_skybridge_alert": {"id":"ch08_skybridge_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":64,"cooldownMs":0,"maxVoices":1,"description":"Above the Quiet City alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch08_skybridge_alert.mp3"},
  "ch08_skybridge_extraction": {"id":"ch08_skybridge_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":64,"cooldownMs":0,"maxVoices":1,"description":"Above the Quiet City extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch08_skybridge_extraction.mp3"},
  "ch09_neural_arcade_base": {"id":"ch09_neural_arcade_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45,"cooldownMs":0,"maxVoices":1,"description":"Tokens of Tomorrow base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch09_neural_arcade_base.mp3"},
  "ch09_neural_arcade_alert": {"id":"ch09_neural_arcade_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45,"cooldownMs":0,"maxVoices":1,"description":"Tokens of Tomorrow alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch09_neural_arcade_alert.mp3"},
  "ch09_neural_arcade_extraction": {"id":"ch09_neural_arcade_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45,"cooldownMs":0,"maxVoices":1,"description":"Tokens of Tomorrow extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch09_neural_arcade_extraction.mp3"},
  "ch10_storm_grid_base": {"id":"ch10_storm_grid_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45.714285714285715,"cooldownMs":0,"maxVoices":1,"description":"Hold the Line base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch10_storm_grid_base.mp3"},
  "ch10_storm_grid_alert": {"id":"ch10_storm_grid_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45.714285714285715,"cooldownMs":0,"maxVoices":1,"description":"Hold the Line alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch10_storm_grid_alert.mp3"},
  "ch10_storm_grid_extraction": {"id":"ch10_storm_grid_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":45.714285714285715,"cooldownMs":0,"maxVoices":1,"description":"Hold the Line extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch10_storm_grid_extraction.mp3"},
  "ch11_central_tower_base": {"id":"ch11_central_tower_base","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":53.333333333333336,"cooldownMs":0,"maxVoices":1,"description":"A City Wakes base layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch11_central_tower_base.mp3"},
  "ch11_central_tower_alert": {"id":"ch11_central_tower_alert","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":53.333333333333336,"cooldownMs":0,"maxVoices":1,"description":"A City Wakes alert layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch11_central_tower_alert.mp3"},
  "ch11_central_tower_extraction": {"id":"ch11_central_tower_extraction","category":"music","gain":1,"loop":true,"loopStart":0,"loopEnd":53.333333333333336,"cooldownMs":0,"maxVoices":1,"description":"A City Wakes extraction layer.","provenance":"Original procedural composition and synthesis; no external samples.","path":"public/assets/audio/ch11_central_tower_extraction.mp3"}
};
