import fs from 'node:fs';import assert from 'node:assert/strict';import {LEVELS} from '../src/content/levels.js';import {AUDIO} from '../src/audio/manifest.js';
let checks=0;
function connectedFloor(tiles){const floor=[];for(let y=0;y<tiles.length;y++)for(let x=0;x<tiles[y].length;x++)if(tiles[y][x]==='.')floor.push([x,y]);if(!floor.length)return false;const queue=[floor[0]],seen=new Set([floor[0].join(',')]);while(queue.length){const [x,y]=queue.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const next=[x+dx,y+dy],key=next.join(',');if(tiles[next[1]]?.[next[0]]==='.'&&!seen.has(key)){seen.add(key);queue.push(next);}}}return seen.size===floor.length;}
function borderIsClosed(tiles,border){for(let y=0;y<20;y++)for(let x=0;x<20;x++)if((x<border||y<border||x>=20-border||y>=20-border)&&tiles[y][x]!=='#')return false;return true;}
assert.deepEqual(LEVELS.map(level=>level.id),Array.from({length:60},(_,index)=>`L${String(index+1).padStart(2,'0')}`));checks++;
for(const l of LEVELS){const {width:w,height:h,tiles,entities}=l.geometry;assert.equal(tiles.length,h);checks++;for(const r of tiles){assert.equal(r.length,w);assert.match(r,/^[#.pe]+$/);checks++;}assert.ok(tiles.join('').includes('p'),`${l.id}: missing Patch field`);assert.ok(tiles.join('').includes('e'),`${l.id}: missing Echo grid`);checks+=2;assert.equal(l.playfields?.size,20,`${l.id}: twin grid size`);const chapter=Number(l.chapterId.slice(1)),expectedBorder=chapter===1?5:chapter===2?4:chapter===3?3:1;assert.equal(l.playfields.border,expectedBorder,`${l.id}: district border`);checks++;for(const field of ['patch','echo'])for(const room of l.playfields[field]){assert.equal(room.tiles.length,20);for(const row of room.tiles){assert.equal(row.length,20);assert.match(row,/^[#.]+$/);}assert.ok(borderIsClosed(room.tiles,expectedBorder),`${l.id}:${room.id} open district border`);assert.ok(connectedFloor(room.tiles),`${l.id}:${room.id} disconnected floor island`);checks+=24;}assert.equal(new Set(entities.map(e=>e.id)).size,entities.length);assert.ok(entities.some(e=>e.id==='exitGate'&&e.blocksMovement&&e.opensAfterEcho),`${l.id}: missing gated exit`);assert.ok(JSON.stringify(l.task.objective).includes('exitActivated'),`${l.id}: exit is not interaction-gated`);assert.ok(['state','actions','reward','practice','policy'].includes(l.learning.puzzleFocus),`${l.id}: missing learning-puzzle focus`);if(chapter>=7)assert.ok(entities.some(e=>e.kind==='echo-hunter'&&e.field==='echo'),`${l.id}: missing Echo patrol`);checks+=4;for(const e of entities){if(l.playfields&&e.field){const room=l.playfields[e.field]?.[e.room??0];assert.ok(room,`${l.id}:${e.id} missing room`);assert.ok(e.x>=0&&e.x<20&&e.y>=0&&e.y<20);if(e.kind!=='boss')assert.notEqual(room.tiles[e.y][e.x],'#',`${l.id}:${e.id}`);}else{assert.ok(e.x>=0&&e.x<w&&e.y>=0&&e.y<h);if(e.kind!=='boss')assert.notEqual(tiles[e.y][e.x],'#',`${l.id}:${e.id}`);}if(!['boss','sentry','echo-hunter','portal','cartridge'].includes(e.kind))assert.ok(fs.existsSync(`public/assets/objects/${e.kind}.png`));checks+=3;}assert.notEqual(l.playfields.patch[l.actors.patchSpawn.room??0].tiles[l.actors.patchSpawn.y][l.actors.patchSpawn.x],'#',`${l.id}: Patch spawn`);assert.notEqual(l.playfields.echo[0].tiles[l.actors.echoSpawn.y][l.actors.echoSpawn.x],'#',`${l.id}: Echo spawn`);checks+=2;assert.equal(JSON.stringify(l),JSON.stringify(JSON.parse(fs.readFileSync(`src/content/levels/${l.id}.json`))));checks++;assert.equal(JSON.stringify(l),JSON.stringify(JSON.parse(fs.readFileSync(`production/layouts/${l.id}.json`))));checks++;for(const cue of l.cues){assert.ok(AUDIO[cue.audio],`${l.id}: missing audio cue ${cue.audio}`);checks++;}}
for(const a of Object.values(AUDIO)){assert.ok(fs.existsSync(a.path));checks++;}
for(const who of ['patch','echo']){const a=JSON.parse(fs.readFileSync(`public/assets/characters/${who}-atlas.json`));for(const anim of Object.values(a.animations)){assert.ok(anim.frames.length>0);for(const f of anim.frames)assert.ok(a.frames[f]);checks++;}}
for(const asset of ['public/assets/ui/echo-heist-logo-v1.png','public/assets/ui/echo-heist-title-v1.png']){assert.ok(fs.existsSync(asset));checks++;}
console.log(`${checks} level, asset, audio, and animation checks passed for the 60-level twelve-district build.`);
